services:
  postgres:
    image: postgres:15-alpine
    container_name: schedule_appointment_db
    environment:
      POSTGRES_DB: schedule_appointment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - schedule_appointment_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d schedule_appointment"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: schedule_appointment_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - schedule_appointment_network

volumes:
  postgres_data:

networks:
  schedule_appointment_network:
    driver: bridge 